server:
  port: 8099
spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sergey
    password: sergey
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect