server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
#          jwk-set-uri: http://localhost:8080/auth/realms/meudominio/protocol/openid-connect/certs
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka
#  instance:
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}
